---
title: "Peer Navigators"
author: "Magali Blanco"
date: "11/17/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, cache=T, cache.comments = F, message = F, warning = F, tidy.opts=list(width.cutoff=60), tidy=TRUE, fig.height = 8)  

# Clear workspace of all objects and unload all extra (non-base) packages
rm(list = ls(all = TRUE))
if (!is.null(sessionInfo()$otherPkgs)) {
  res <- suppressWarnings(
    lapply(paste('package:', names(sessionInfo()$otherPkgs), sep=""),
      detach, character.only=TRUE, unload=TRUE, force=TRUE))
}

pacman::p_load(readxl, table1, tidyverse)

pn_initial <- read_excel("Data/peer navigator initial questionnaires.xlsx")
pn_training <- read_excel("Data/training quizzes.xlsx")

source("Var&Fns.R")

```

\newpage   
Peer Navigator Initial Questionnaire   

```{r}
### --> ?? no "English as primary langugae" Q. get from benefits group?

```

```{r}

#format column types 
pn_initial <- pn_initial %>%
  mutate(
    edu = factor(edu, levels = c(seq(0,5), 999), 
                 labels = c("less than HS", "finished HS or GED", "some college", "finished college", "trade/vocational school", "other", "prefer not to answer")),
    inury = factor(injury, levels = c(0, 1, 999), 
                   labels = c("no", "yes", "prefer not to answer")),
    workers_comp =  factor(workers_comp, levels = c(0, 1, 999), 
                   labels = c("no", "yes", "prefer not to answer")),
    chronic_pain =  factor(chronic_pain, levels = c(0, 1, 999), 
                   labels = c("no", "yes", "prefer not to answer")),
    gender =  factor(gender, levels = c(seq(0,5), 999), 
                   labels = c("female", "male", "transgender female", "transgender male", "gender non-conforming", "not listed", "prefer not to answer")),
    hispanic =  factor(hispanic, levels = c(0, 1, 999), 
                   labels = c("no", "yes", "prefer not to answer")),
    race_all =  factor(race_all, levels = c(seq(1,7), 999), 
                   labels = c("American Indian/Alaska Native", "Asian", "Black/African American", "Native Hawaiian/OtherPacific Islander", "White", "Other", "More than one race", "prefer not to answer")),
  ) 

### ---> 
### rename columns 
label(pn_initial$age) <- "Age"
label(pn_initial$gender) <- "Gender"
label(pn_initial$race_all) <- "Race"
label(pn_initial$edu) <- "Education"
label(pn_initial$injury) <- "Injury"
label(pn_initial$workers_comp) <- "Have Filed a Worker’s Compensation Claim in the Past"
label(pn_initial$chronic_pain) <- "Have had an Injury Related to HCA work"

units(pn_initial$age) <- "years"


# example
t1 <- table1(~age + gender + race_all + edu + 
               injury + workers_comp + chronic_pain,
             data = pn_initial, 
             render.continuous = my.render.cont,
             render.categorical = my.render.cat
             )




t1

```

Peer Navigator Quiz

```{r}
### --> analyze pn_training w/ and w/o sup
### --> Quizzes: a) Do analysis on each individual question, b) Show all 3 time periods, c) Use: pre 1 vs post 2 for final t-test analysis 

```

```{r}

```


